theme: jekyll-theme-hacker
title: WootzApp
logo: /image/logo2.png
description: "WootzApp - We fork Chromium to build a browser which nudges users to complete tasks for AI, and get paid for it."

# Build settings
show_downloads: true
markdown: kramdown
